"""Carga el catálogo de zapatillas desde sneaks_data.json.

Uso:
    python seed.py           # carga productos solo si la tabla está vacía
    python seed.py --force   # recrea todas las tablas (borra usuarios y pedidos) y recarga el catálogo
"""
import json
import os
import sys

from database import db, init_db
from models.product import Product
from services.user_service import UserService

# Path to the JSON file generated by sneaks-fetcher
DATA_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "sneaks_data.json")

# Cuenta usada por el botón "Cuenta de Prueba" del login
DEMO_USER = {"name": "Usuario Demo", "email": "demo@clickandbuy.cl", "password": "demo1234"}


def load_products(path=DATA_FILE):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def seed_products(products_data, force=False):
    """Inserta los productos y devuelve (insertados, omitidos). Requiere app context."""
    if force:
        # Drop all tables and recreate them to apply schema changes cleanly
        db.drop_all()
        init_db()
    elif Product.query.count() > 0:
        return 0, 0

    inserted = 0
    skipped = 0
    for p in products_data:
        # Validate minimum required fields
        if not p.get("name") or not p.get("brand") or not p.get("price"):
            skipped += 1
            continue

        db.session.add(Product(
            name=p["name"],
            brand=p["brand"],
            category=p.get("category", "Lifestyle"),
            price=p["price"],
            price_usd=p.get("price_usd", 0),
            description=p.get("description", ""),
            image_url=p.get("image_url", ""),
            stock=p.get("stock", 10),
            sizes=p.get("sizes", []),
            style_id=p.get("style_id", ""),
            colorway=p.get("colorway", ""),
            release_date=p.get("release_date", ""),
            resell_links=p.get("resell_links", {})
        ))
        inserted += 1

    db.session.commit()
    return inserted, skipped


def ensure_demo_user():
    """Crea la cuenta demo si no existe. Devuelve True si la creó."""
    return UserService.create_user(DEMO_USER["name"], DEMO_USER["email"], DEMO_USER["password"]) is not None


def print_summary():
    count = db.func.count(Product.id)
    brands = db.session.query(Product.brand, count).group_by(Product.brand).order_by(count.desc()).all()
    categories = db.session.query(Product.category, count).group_by(Product.category).order_by(count.desc()).all()

    print("\n[RESUMEN]")
    print("   Marcas:")
    for b, c in brands:
        print(f"     • {b}: {c} productos")
    print("   Categorías:")
    for cat, c in categories:
        print(f"     • {cat}: {c} productos")


def run(argv):
    """Ejecuta el seed dentro de un app context ya activo."""
    if not os.path.exists(DATA_FILE):
        print(f"[ERROR] No se encontro {DATA_FILE}")
        print("   Ejecuta primero: cd ../sneaks-fetcher && node fetch.js")
        return 1

    force = "--force" in argv
    products_data = load_products()
    print(f"[INFO] {len(products_data)} productos en sneaks_data.json")

    inserted, skipped = seed_products(products_data, force=force)
    if ensure_demo_user():
        print(f"[OK] Cuenta demo creada: {DEMO_USER['email']} / {DEMO_USER['password']}")

    if inserted == 0 and skipped == 0:
        print("[INFO] La base ya tiene productos. Usa --force para recrearla desde cero.")
        return 0

    print(f"[OK] {inserted} productos insertados exitosamente.")
    if skipped > 0:
        print(f"[WARN] {skipped} productos omitidos (datos incompletos).")
    print_summary()
    return 0


def main(argv):
    # Fix Windows console encoding
    if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # type: ignore

    from app import create_app
    with create_app().app_context():
        return run(argv)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
