import json
import os
import sys

# Fix Windows console encoding
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from database import init_db, get_connection

# Path to the JSON file generated by sneaks-fetcher
DATA_FILE = os.path.join(os.path.dirname(__file__), "sneaks_data.json")

init_db()

# Load products from the JSON file
if not os.path.exists(DATA_FILE):
    print(f"[ERROR] No se encontro {DATA_FILE}")
    print("   Ejecuta primero: cd ../sneaks-fetcher && node fetch.js")
    exit(1)

with open(DATA_FILE, "r", encoding="utf-8") as f:
    products = json.load(f)

print(f"[INFO] Cargando {len(products)} productos desde sneaks_data.json...")

conn = get_connection()

# Drop and recreate the products table to apply schema changes
conn.execute("DROP TABLE IF EXISTS order_items")
conn.execute("DROP TABLE IF EXISTS orders")
conn.execute("DROP TABLE IF EXISTS products")

# Recreate tables with new schema
conn.execute("""
    CREATE TABLE IF NOT EXISTS products (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        brand TEXT NOT NULL,
        category TEXT NOT NULL,
        price REAL NOT NULL,
        price_usd REAL,
        description TEXT,
        image_url TEXT,
        stock INTEGER DEFAULT 0,
        sizes TEXT DEFAULT '[]',
        style_id TEXT DEFAULT '',
        colorway TEXT DEFAULT '',
        release_date TEXT DEFAULT '',
        resell_links TEXT DEFAULT '{}',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
""")

conn.execute("""
    CREATE TABLE IF NOT EXISTS orders (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER NOT NULL,
        total REAL NOT NULL,
        status TEXT DEFAULT 'pending',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES users(id)
    )
""")

conn.execute("""
    CREATE TABLE IF NOT EXISTS order_items (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        order_id INTEGER NOT NULL,
        product_id INTEGER NOT NULL,
        size TEXT NOT NULL,
        quantity INTEGER NOT NULL,
        price REAL NOT NULL,
        FOREIGN KEY (order_id) REFERENCES orders(id),
        FOREIGN KEY (product_id) REFERENCES products(id)
    )
""")

# Insert products
inserted = 0
skipped = 0

for p in products:
    # Validate minimum required fields
    if not p.get("name") or not p.get("brand") or not p.get("price"):
        skipped += 1
        continue

    conn.execute(
        """INSERT INTO products (name, brand, category, price, price_usd, description,
           image_url, stock, sizes, style_id, colorway, release_date, resell_links)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (
            p["name"],
            p["brand"],
            p.get("category", "Lifestyle"),
            p["price"],
            p.get("price_usd", 0),
            p.get("description", ""),
            p.get("image_url", ""),
            p.get("stock", 10),
            json.dumps(p.get("sizes", [])),
            p.get("style_id", ""),
            p.get("colorway", ""),
            p.get("release_date", ""),
            json.dumps(p.get("resell_links", {})),
        ),
    )
    inserted += 1

conn.commit()
conn.close()

print(f"[OK] {inserted} productos insertados exitosamente.")
if skipped > 0:
    print(f"[WARN] {skipped} productos omitidos (datos incompletos).")

# Print summary
print(f"\n[RESUMEN]")
conn = get_connection()
brands = conn.execute("SELECT brand, COUNT(*) as c FROM products GROUP BY brand ORDER BY c DESC").fetchall()
categories = conn.execute("SELECT category, COUNT(*) as c FROM products GROUP BY category ORDER BY c DESC").fetchall()
conn.close()

print("   Marcas:")
for b in brands:
    print(f"     • {b['brand']}: {b['c']} productos")
print("   Categorías:")
for c in categories:
    print(f"     • {c['category']}: {c['c']} productos")
