import json
import os
import sys

# Fix Windows console encoding
if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace") # type: ignore

from app import create_app
from database import db
from models.product import Product
from models.order import Order, OrderItem
from models.user import User

# Path to the JSON file generated by sneaks-fetcher
DATA_FILE = os.path.join(os.path.dirname(__file__), "sneaks_data.json")

if not os.path.exists(DATA_FILE):
    print(f"[ERROR] No se encontro {DATA_FILE}")
    print("   Ejecuta primero: cd ../sneaks-fetcher && node fetch.js")
    exit(1)

with open(DATA_FILE, "r", encoding="utf-8") as f:
    products_data = json.load(f)

print(f"[INFO] Cargando {len(products_data)} productos desde sneaks_data.json...")

app = create_app()

with app.app_context():
    # Drop all tables and recreate them to apply schema changes cleanly
    db.drop_all()
    db.create_all()

    inserted = 0
    skipped = 0

    for p in products_data:
        # Validate minimum required fields
        if not p.get("name") or not p.get("brand") or not p.get("price"):
            skipped += 1
            continue

        product = Product(
            name=p["name"],
            brand=p["brand"],
            category=p.get("category", "Lifestyle"),
            price=p["price"],
            price_usd=p.get("price_usd", 0),
            description=p.get("description", ""),
            image_url=p.get("image_url", ""),
            stock=p.get("stock", 10),
            sizes=p.get("sizes", []),
            style_id=p.get("style_id", ""),
            colorway=p.get("colorway", ""),
            release_date=p.get("release_date", ""),
            resell_links=p.get("resell_links", {})
        )
        db.session.add(product)
        inserted += 1

    db.session.commit()

    print(f"[OK] {inserted} productos insertados exitosamente.")
    if skipped > 0:
        print(f"[WARN] {skipped} productos omitidos (datos incompletos).")

    # Print summary
    print(f"\n[RESUMEN]")
    brands = db.session.query(Product.brand, db.func.count(Product.id)).group_by(Product.brand).order_by(db.func.count(Product.id).desc()).all()
    categories = db.session.query(Product.category, db.func.count(Product.id)).group_by(Product.category).order_by(db.func.count(Product.id).desc()).all()

    print("   Marcas:")
    for b, count in brands:
        print(f"     • {b}: {count} productos")
    print("   Categorías:")
    for c, count in categories:
        print(f"     • {c}: {count} productos")
